### ISSUE TITLE
RATS slightly modifies image geometry

### ISSUE THREAD

**Issue by salma1601** [sammba-mri/sammba-mri#102]
from AFNI 3dinfo: original is
>Geometry String: "MATRIX(-0.15625,2.907935e-20,1.913506e-17,6.17924,3.851860e-33,0.104166,-0.000356,-9.610503,-1.91351e-17,-0.000237,-0.15625,7.450568):96,192,64"

while the mask has geometry
>Geometry String: "MATRIX(-0.15625,2.914767e-20,1.913506e-17,6.17924,-1.02483e-22,0.104166,-0.000358,-9.610503,-1.91351e-17,-0.000239,-0.15625,7.450568):96,192,64"

(Note the -0.000239  instead of -0.000237)
So this is not large, but enough to make the application of mask with 3dCalc throw a warning 
> Template space of dataset /tmp/test_design/MINDt-MLRS-28944_20170712_153818_04_T1_FLASH_3D_fixedSIAP_bf8_unifized_for_brain_mask_brain_mask.nii.gz does not match space of first dataset

**Comment by nadkarni-na** [comment]
Have to admit, never noticed this as RATS only makes a mask, whose geometry is never propagated. ok so need fslcpgeom or the equivalent nibabel python to replace the mask header with that of the head.

**Comment by salma1601** [comment]
addressed in #101. Closing

**Comment by salma1601** [comment]
Reopening because the problem has not been solved.
