### ISSUE TITLE
improve registration.anats_to_common code

### ISSUE THREAD

**Issue by salma1601** [sammba-mri/sammba-mri#149]
I think that the code for the nonlinear iterations part is not easy to follow. Each iteration relies on the AFNI 3dQwarp function. The 3dQwarp function is itself iterative and must be given a stopping criteria. There are two ways for this: either setting its maximum refinement level `maxlev` or specifying the minimal path size `minpatch`.
As discussed with @garincle, our strategy compromises 2 steps. In the first step we set the `maxlev` (going from refinement level `nonlinear_levels[n_iter -1] + 1` [to refinement level `nonlinear_levels[n_iter]`](https://github.com/sammba-mri/sammba-mri/blob/master/sammba/registration/struct.py#L586)). In the second step we set its `minpatch` (so starting from refinement level `nonlinear_levels[n_iter -1] + 1` and [stopping when patch size reaches `nonlinear_minimal_patches[0]`, then `nonlinear_minimal_patches[1]` etc](https://github.com/sammba-mri/sammba-mri/blob/master/sammba/registration/struct.py#L599))

These two steps have been merged together in the code by [defining `levels_minpatches`](https://github.com/sammba-mri/sammba-mri/blob/master/sammba/registration/struct.py#L545) but I think this makes the code obscure for maintainers. I am in favour of doing two separate loops, first loop calling `qwarp` with  `maxlev` option and second loop using `qwarp2` with `minpatch`

**Comment by marinacelestine** [comment]
I think we can close this issue

**Comment by salma1601** [comment]
ok, closing
