### ISSUE TITLE
Shear in mouse 1369 of test-retest dataset

### ISSUE THREAD

**Issue by salma1601** [sammba-mri/sammba-mri#19]
When trying to set the qform equal to the sform for this mouse, I am receiving an error because it contains shear components while according to the nibabel `set_qform` function,

>The qform transform only encodes translations, rotations and zooms. If there are shear components
to the `affine` transform, and `strip_shears` is True (the default), the written qform gives the
closest approximation where the rotation matrix is orthogonal. This is to allow quaternion representation. The orthogonal representation enforces orthogonal axes.

There wasn't such a problem for other mice, so I was wondering whether we should allow strip shears or not. 
@nadkarni-na Have you encountered such a problem ?

**Comment by nadkarni-na** [comment]
should be fine, tho am surprised it only has a problem with shears; if it wants to be that strict with qform usage it should have a problem with zooms too (qform specifies the relationship to the scanner which can only ever be a rigid-body transform)

**Comment by salma1601** [comment]
Ok thanks, then I will set `strip_shears=True`
