### ISSUE TITLE
dicom file extensions

### ISSUE THREAD

**Issue by nadkarni-na** [sammba-mri/sammba-mri#41]
https://github.com/sammba-mri/sammba-mri/blob/f89980bd86cba34084677d528563efd3b3333005/sammba/io_conversions/bruker_dicom.py#L15

these are exclusively .dcm on Bruker systems. Given there is no public official ParaVision directory and file format specification, all non EnIm*.dcm possibilities (including .dicom and especially .ima) should be excluded to avoid inputting files that would crash the converter

**Comment by salma1601** [comment]
OK, thanks for pointing this ! Do you want to do a PR ?

**Comment by nadkarni-na** [comment]
done, though in the mean time found another issue that needs to be opened
