### ISSUE TITLE
functional output resolution

### ISSUE THREAD

**Issue by nadkarni-na** [sammba-mri/sammba-mri#46]
have an option to use a resolution other than that of the template

**Comment by salma1601** [comment]
you mean in the function `registration.func._func_to_template` ?

**Comment by nadkarni-na** [comment]
Yes, and any other function that may align images to a template. A simple way to do it would be for the function to create a temporary version of the template that is downsampled to the required resolution, then use this downsampled template as the master to 3dNwarpApply.

To be clear, this downsampled template would only ever be used for application of transforms, not for the calculation of them, which should be done to the original template the user enters. That said, if we want, we could add yet another option to choose a resolution for the original calculation too.

So maybe have two options. One is the resolution for calculation of the transform (this already exists for per slice registration), and another for its application. Of course, this could lead to silly situations, so if someone asks for a 100μm resolution on a 200μm template they're just wasting computing power, but that would be their fault.

**Comment by salma1601** [comment]
I am adding importance to this issue, because Clement need it for his ongoing analyses.
So if I understand well, we need just to add `-dxyz` flag with a target resolution here ?
https://github.com/sammba-mri/sammba-mri/blob/master/sammba/registration/func.py#L545

**Comment by nadkarni-na** [comment]
this looks solved...

**Comment by nadkarni-na** [comment]
? close?

**Comment by salma1601** [comment]
@garincle is your resolution problem solved ? we want to close this issue

**Comment by garincle** [comment]
Just wait the begining of the next week i will tell you on my new data if
everithing is ok


2018-01-12 11:54 GMT+01:00 salma1601 <notifications@github.com>:
