### ISSUE TITLE
bias corection (3dUnifize) strategy is critical in brain mask computation

### ISSUE THREAD

**Issue by salma1601** [sammba-mri/sammba-mri#52]
I think it is worth comparing `RATS_MM` brain mask quality to `nilearn.masking.compute_epi_mask`. If results are comparable, I am in favour to drop RATS_MM dependency. This tool is not really open, one must fill a form to download it, and cite 2 papers when using it, which makes the list of citations too long when sammba is used.

**Comment by nadkarni-na** [comment]
This would require extensive tests. The accuracy of RATS_MM on the vast majority of our images is very useful for generating dilated weight masks, improving registration performance and so on.

**Comment by nadkarni-na** [comment]
Can you expose -clfrac? Varying makes a big difference with some of our datasets

**Comment by salma1601** [comment]
Ok.
I also saw that there is an option `-T2` in 3dUnifize to treat the input as if it were T2-weighted, rather than T1-weighted. Do you think this will improve things for our data ?

**Comment by nadkarni-na** [comment]
From experience it won't, but at this point it might be a good idea to expose all the 3dUnifize options just in case they are ever useful

**Comment by nadkarni-na** [comment]
Yet another potential solution: at the moment we have [maxrot = 90](https://github.com/sammba-mri/sammba-mri/blob/a457a02c338de13507c4d3ddc37425d573760018/sammba/registration/struct.py#L687). This is a historical choice from when I was dealing with really messed-up images of uncertain orientation. In reality it allows to much margin for rotating badly-extracted images. Reducing it to 45, or maybe even the default of 30 should limit 3dAllineate from making bad choice with badly-extracted brains. From memory I have never seen in the wild images oriented more than 45 degrees from the biological ideal.

**Comment by salma1601** [comment]
So, to summarize there are 2 options:
1- keep things as they are now, that is for good images default to `brain_from_raw=False`, and for 'bad' images users are encouraged to `brain_from_raw=True`.
2- Replace `brain_from_raw=False` by something like `restrict_bias_correction=False`. So for good images only one unifization is done with default parameters, and for bad ones  `restrict_bias_correction=True` where internally unifization is done twice with clfrac tuned.

A part from making things more complicated (more code, one additionnal unifize), what are the benefits of 2 over 1 ?

**Comment by nadkarni-na** [comment]
2 will work with everything, 1 will not

**Comment by salma1601** [comment]
Do you mean no more need tfor a bias_correction option, just do 2 unifizations with clfrac 0.2 and 0.5 for every possible image ?

**Comment by nadkarni-na** [comment]
Yep, though the clfrac for both needs to be tunable, with defaults of 0.2

**Comment by salma1601** [comment]
Ok

**Comment by nadkarni-na** [comment]
actually by default just accept the afni defaults, which have evolved over time. for decent images a wide range of Rbt and clfrac work. at any given point in the future, regardless of what the afni defaults are at that point, if the user has poor images they can change clfrac and rbt however they like

**Comment by salma1601** [comment]
working on it. Do you think this strategy is worth to be applied also in `anats_to_template` function ?

**Comment by nadkarni-na** [comment]
yes

**Comment by salma1601** [comment]
functional to anatomical coregistration ?

**Comment by nadkarni-na** [comment]
if ridgidbodyreg=no, no. if =yes, possibly, but it's too much of an edge case even for me given all the other stuff that needs to be done

**Comment by salma1601** [comment]
Ok so I am going to use this strategy to anats registration for the moment. Thanks

**Comment by salma1601** [comment]
I am going to rename this issue, as what has been discussed essentially was unifization strategy to succeed in brain extraction

**Comment by salma1601** [comment]
exactly, so this can be done for instance the following
```Python
brain_extraction_unifize_kwargs = {'rbt': 19.5, 'cl_frac': .5}
```
Meaning you enter a dictionary with all the parameters you want to change.
Are you suggesting that I do not force the `cl_frac=0.2` but keep it as AFNI default?

**Comment by nadkarni-na** [comment]
ok and yes

**Comment by salma1601** [comment]
closing, as fixed by #59

**Comment by nadkarni-na** [comment]
Just found a [bug](https://github.com/sammba-mri/sammba-mri/blob/abc5641678bab6b7975f656d758b100bae6da383/sammba/registration/struct.py#L172)
This code does not overwrite the brain_extraction Unifize files, so the rest of the script processes the brain_extraction ones, not the second set created here.

Ideally they should both have different names so that both are saved so that the difference between them can be compared visually, but I cannot figure out how to easily automate changes in nipype suffixes.

**Comment by nadkarni-na** [comment]
Actually I just figured it out, will commit and PR later

**Comment by salma1601** [comment]
Ok
Meanwhile, you can also try use the option `caching=True` which allows to save every preprocessing outputs. It is a little bit experimental for the moment so it may fail or you may have some pain guessing to which preprocessing correspond which directory.
