### ISSUE TITLE
registration.anats_to_common can't go beyond level 8, partially ignores minpatch

### ISSUE THREAD

**Issue by nadkarni-na** [sammba-mri/sammba-mri#72]
Am still having a problem mentioned in #65; for some reason, during the -minpatch loops, -maxlev n is added to the end of the 3dQwarp command passed to the shell even though -maxlev should not appear at all (as seen both by ps -aux in real time, and also doing 3dinfo on the resulting images). n is the maxlev used in the final maxlev loop. The effect is also visible in the nipype verbose output.

The end result is that whatever minpatch(es) is/are supplied, the contradictory -maxlev n creates a contradiction. The decision 3dQwarp makes is just to advance 1 level beyond n.

I've got this problem with three very different sets of data. The logs are quite large and the datasets not public, @salma1601 when you are at MIRCen msg me then I'll DM you.

**Comment by salma1601** [comment]
Ok. I tried this on Pauline's sample of 4 rats, and didn't have this issue. Did you experience it with this data sample ?

**Comment by salma1601** [comment]
another point is that as you have seen, nipype does not at all change parameters set up by the user and in the Qwarp specific case, there is no default value for maxlev. So for me this looks like an internal bug of our qwarp loop.

**Comment by salma1601** [comment]
@nadkarni-na  Still can't reproduce the bug. Here is the last 3dQwarp command, there is no maxlev in it
>3dQwarp -base /tmp/pauline/template12/nipype_mem/sammba-externals-nipype-interfaces-afni-preprocess-Qwarp/0705c6e7807728a51bc91e197c3516aa/warped_2iters_hetemplate_filenameads_tstat.nii.gz -source /tmp/pauline/template12/nipype_mem/sammba-externals-nipype-interfaces-afni-preprocess-Qwarp/0705c6e7807728a51bc91e197c3516aa/MSME_MIRCen_RatBrain_atlas_bf7_3_Unifized_for_brain_extraction_resample.nii.gz -inilev 8 -iniwarp /tmp/pauline/template12/nipype_mem/sammba-externals-nipype-interfaces-afni-utils-Resample/fffa8e85ad675f09df4510f128e96e69/MSME_MIRCen_RatBrain_atlas_bf7_3_Unifized_for_brain_extraction_resample_warped2_WARP.nii.gz -iwarp -minpatch 11 -noneg -prefix /tmp/pauline/template12/nipype_mem/sammba-externals-nipype-interfaces-afni-utils-Resample/fffa8e85ad675f09df4510f128e96e69/MSME_MIRCen_RatBrain_atlas_bf7_3_Unifized_for_brain_extraction_resample_warped3.nii.gz -weight /tmp/pauline/template10/affbrainsunionmaskdil5.nii.gz

**Comment by nadkarni-na** [comment]
Is this confirmed by 3dinfo and the nipype log?

**Comment by salma1601** [comment]
3dinfo output
>[sb250965@finn: Wed Jan 10 15:32:48 2018] 3dQwarp -base /tmp/pauline/template12/nipype_mem/sammba-externals-nipype-interfaces-afni-preprocess-Qwarp/0705c6e7807728a51bc91e197c3516aa/warped_2iters_hetemplate_filenameads_tstat.nii.gz -source /tmp/pauline/template12/nipype_mem/sammba-externals-nipype-interfaces-afni-preprocess-Qwarp/0705c6e7807728a51bc91e197c3516aa/MSME_MIRCen_RatBrain_atlas_bf7_3_Unifized_for_brain_extraction_resample.nii.gz -inilev 8 -iniwarp /tmp/pauline/template12/nipype_mem/sammba-externals-nipype-interfaces-afni-utils-Resample/fffa8e85ad675f09df4510f128e96e69/MSME_MIRCen_RatBrain_atlas_bf7_3_Unifized_for_brain_extraction_resample_warped2_WARP.nii.gz -iwarp -minpatch 11 -noneg -prefix /tmp/pauline/template12/nipype_mem/sammba-externals-nipype-interfaces-afni-utils-Resample/fffa8e85ad675f09df4510f128e96e69/MSME_MIRCen_RatBrain_atlas_bf7_3_Unifized_for_brain_extraction_resample_warped3.nii.gz -weight /tmp/pauline/template10/affbrainsunionmaskdil5.nii.gz

**Comment by nadkarni-na** [comment]
and according to the nipype output it went all the way down to 11x11x11 ? Which should be about level 10?

**Comment by salma1601** [comment]
yes
>80110-16:10:30,678 workflow INFO:
	 Executing node 0a284c17c505ab1b0a6d2f1b85ef8a70 in dir: /tmp/pauline/template12/nipype_mem/sammba-externals-nipype-interfaces-afni-preprocess-Qwarp/0a284c17c505ab1b0a6d2f1b85ef8a70
180110-16:10:30,693 workflow INFO:
	 Running node "0a284c17c505ab1b0a6d2f1b85ef8a70" ("sammba.externals.nipype.interfaces.afni.preprocess.Qwarp"), a CommandLine Interface with command:
3dQwarp -base /tmp/pauline/template12/nipype_mem/sammba-externals-nipype-interfaces-afni-preprocess-Qwarp/0a284c17c505ab1b0a6d2f1b85ef8a70/warped_2iters_hetemplate_filenameads_tstat.nii.gz -source /tmp/pauline/template12/nipype_mem/sammba-externals-nipype-interfaces-afni-preprocess-Qwarp/0a284c17c505ab1b0a6d2f1b85ef8a70/MSME_MIRCen_RatBrain_atlas_bf5_0_Unifized_for_brain_extraction_resample.nii.gz -inilev 8 -iniwarp /tmp/pauline/template12/nipype_mem/sammba-externals-nipype-interfaces-afni-utils-Resample/d62f6b16c790477dde8daeec81bdae09/MSME_MIRCen_RatBrain_atlas_bf5_0_Unifized_for_brain_extraction_resample_warped2_WARP.nii.gz -iwarp -minpatch 11 -noneg -prefix /tmp/pauline/template12/nipype_mem/sammba-externals-nipype-interfaces-afni-utils-Resample/d62f6b16c790477dde8daeec81bdae09/MSME_MIRCen_RatBrain_atlas_bf5_0_Unifized_for_brain_extraction_resample_warped3.nii.gz -weight /tmp/pauline/template10/affbrainsunionmaskdil5.nii.gz.
180110-16:10:30,745 interface INFO:
	 stderr 2018-01-10T16:10:30.745254:++ OpenMP thread count = 15
180110-16:10:30,748 interface INFO:
	 stderr 2018-01-10T16:10:30.748553:++ 3dQwarp: AFNI version=Debian-16.2.07~dfsg.1-5~nd14.04+1 (Jun 12 2017) [64-bit]
180110-16:10:30,748 interface INFO:
	 stderr 2018-01-10T16:10:30.748553:++ Authored by: Zhark the (Hermite) Cubically Warped
180110-16:10:31,324 interface INFO:
	 stderr 2018-01-10T16:10:31.324023:++ -noneg converted 3894 source voxels to 0
180110-16:10:31,463 interface INFO:
	 stderr 2018-01-10T16:10:31.463565:++ Dataset zero-pad: xbot=18 xtop=18  ybot=0 ytop=18  zbot=9 ztop=11 voxels
180110-16:10:31,544 interface INFO:
	 stderr 2018-01-10T16:10:31.544582: + Extended/padded iniwarp to match base volume: 0 0  0 0  1 0 voxels
180110-16:10:31,555 interface INFO:
	 stderr 2018-01-10T16:10:31.555687:++ +++++++++++ Begin warp optimization:  base=/tmp/pauline/template12/nipype_mem/sammba-externals-nipype-interfaces-afni-preprocess-Qwarp/0a284c17c505ab1b0a6d2f1b85ef8a70/warped_2iters_hetemplate_filenameads_tstat.nii.gz  source=/tmp/pauline/template12/nipype_mem/sammba-externals-nipype-interfaces-afni-preprocess-Qwarp/0a284c17c505ab1b0a6d2f1b85ef8a70/MSME_MIRCen_RatBrain_atlas_bf5_0_Unifized_for_brain_extraction_resample.nii.gz
180110-16:10:31,944 interface INFO:
	 stderr 2018-01-10T16:10:31.944801:++ AFNI warpomatic: 196 x 178 x 120 volume ; autobbox = 50..145 47..118 13..108 [clock= 1s 195ms]
180110-16:11:01,562 interface INFO:
	 stderr 2018-01-10T16:11:01.562129:lev=8 patch=19x17x13 [clock= 1s 280ms][first cost=32.81344] .................. done [cost:32.81344==>32.58487 ; 995 patches optimized, 589 skipped]
180110-16:11:46,43 interface INFO:
	 stderr 2018-01-10T16:11:46.043505:lev=9 patch=15x13x11 [clock= 30s 880ms]......................... done [cost:32.58487==>41.52152 ; 2009 patches optimized, 1183 skipped]
180110-16:12:48,41 interface INFO:
	 stderr 2018-01-10T16:12:48.041349:lev=10 patch=11x11x11 [clock= 1m 15s 370ms]................................ done [cost:41.52152==>47.78472 ; 3222 patches optimized, 1832 skipped]
180110-16:12:48,878 interface INFO:
	 stderr 2018-01-10T16:12:48.878324:++ ========== total number of parameters 'optimized' = 149424
180110-16:12:49,341 interface INFO:
	 stderr 2018-01-10T16:12:49.341370:++ Output dataset /tmp/pauline/template12/nipype_mem/sammba-externals-nipype-interfaces-afni-utils-Resample/d62f6b16c790477dde8daeec81bdae09/MSME_MIRCen_RatBrain_atlas_bf5_0_Unifized_for_brain_extraction_resample_warped3.nii.gz
180110-16:12:51,509 interface INFO:
	 stderr 2018-01-10T16:12:51.509207:++ Output dataset /tmp/pauline/template12/nipype_mem/sammba-externals-nipype-interfaces-afni-utils-Resample/d62f6b16c790477dde8daeec81bdae09/MSME_MIRCen_RatBrain_atlas_bf5_0_Unifized_for_brain_extraction_resample_warped3_WARP.nii.gz
180110-16:12:54,251 interface INFO:
	 stderr 2018-01-10T16:12:54.250948:++ Inverting warp *****........:.....
180110-16:12:56,321 interface INFO:
	 stderr 2018-01-10T16:12:56.321594:++ Output dataset /tmp/pauline/template12/nipype_mem/sammba-externals-nipype-interfaces-afni-utils-Resample/d62f6b16c790477dde8daeec81bdae09/MSME_MIRCen_RatBrain_atlas_bf5_0_Unifized_for_brain_extraction_resample_warped3_WARPINV.nii.gz
180110-16:12:56,322 interface INFO:
	 stderr 2018-01-10T16:12:56.322016:++ ===== clock time = 2m 25s 547ms

**Comment by nadkarni-na** [comment]
In which case our qwarp loop does not have an internal bug. the only info I can add for now is that I am running Python 2.7.12. I'll replace the qwarp() command with a subprocess call later and see what happens

**Comment by salma1601** [comment]
I can't see a relationship with python version or nipype or subprocess. Do you have the last master version ? In this case, can you just run your script with `caching=True` and `verbose=3` and send me the nipype printed message for the last Qwarp step with exactly the 4 rat images ? As a first step I want to be sure we are using **exactly** the same code on the same data

**Comment by nadkarni-na** [comment]
I have the latest master and was using verbose = 3. The only difference was not using caching. The relevant part of the nipype log looked like this:

180105-14:41:00,292 interface INFO:
	 stderr 2018-01-05T14:41:00.292289:++ OpenMP thread count = 4
180105-14:41:00,299 interface INFO:
	 stderr 2018-01-05T14:41:00.299213:++ 3dQwarp: AFNI version=Debian-16.2.07~dfsg.1-5~nd16.04+1 (Jun 12 2017) [64-bit]
180105-14:41:00,299 interface INFO:
	 stderr 2018-01-05T14:41:00.299213:++ Authored by: Zhark the (Hermite) Cubically Warped
180105-14:41:01,305 interface INFO:
	 stderr 2018-01-05T14:41:01.305180:++ -noneg converted 3894 source voxels to 0
180105-14:41:01,573 interface INFO:
	 stderr 2018-01-05T14:41:01.573728:++ Dataset zero-pad: xbot=18 xtop=18  ybot=0 ytop=18  zbot=11 ztop=11 voxels
180105-14:41:01,896 interface INFO:
	 stderr 2018-01-05T14:41:01.896109: + Extended/padded iniwarp to match base volume: 0 0  0 0  1 0 voxels
180105-14:41:01,925 interface INFO:
	 stderr 2018-01-05T14:41:01.925344:++ +++++++++++ Begin warp optimization:  base=/mnt/c/Users/nadka/Downloads/forPR/template2/warped_2iters_hetemplate_filenameads_tstat.nii.gz  source=/mnt/c/Users/nadka/Downloads/forPR/template2/MSME_MIRCen_RatBrain_atlas_bf5_1_Unifized_for_brain_extraction_resample.nii.gz
180105-14:41:02,793 interface INFO:
	 stderr 2018-01-05T14:41:02.793168:++ AFNI warpomatic: 196 x 178 x 122 volume ; autobbox = 47..147 45..119 12..110 [clock= 2s 492ms]
180105-14:44:31,977 interface INFO:
	 stderr 2018-01-05T14:44:31.977096:lev=8 patch=19x17x13 [clock= 2s 986ms][first cost=27.70704] ........................ done [cost:27.70704==>27.48046 ; 1120 patches optimized, 563 skipped]
180105-14:44:39,941 interface INFO:
	 stderr 2018-01-05T14:44:39.941681:++ ========== total number of parameters 'optimized' = 26880
180105-14:44:40,691 interface INFO:
	 stderr 2018-01-05T14:44:40.691697:++ Output dataset /mnt/c/Users/nadka/Downloads/forPR/template2/MSME_MIRCen_RatBrain_atlas_bf5_1_Unifized_for_brain_extraction_resample_warped3.nii.gz
180105-14:44:44,51 interface INFO:
	 stderr 2018-01-05T14:44:44.051009:++ Output dataset /mnt/c/Users/nadka/Downloads/forPR/template2/MSME_MIRCen_RatBrain_atlas_bf5_1_Unifized_for_brain_extraction_resample_warped3_WARP.nii.gz
180105-14:45:05,199 interface INFO:
	 stderr 2018-01-05T14:45:05.199735:++ Inverting warp *****........:....
180105-14:45:08,568 interface INFO:
	 stderr 2018-01-05T14:45:08.568068:++ Output dataset /mnt/c/Users/nadka/Downloads/forPR/template2/MSME_MIRCen_RatBrain_atlas_bf5_1_Unifized_for_brain_extraction_resample_warped3_WARPINV.nii.gz
180105-14:45:08,568 interface INFO:
	 stderr 2018-01-05T14:45:08.568534:++ ===== clock time = 4m 8s 221ms

**Comment by nadkarni-na** [comment]
So it didn't go beyond 19x17x13

**Comment by salma1601** [comment]
are you sure this is the last Qwarp ? Do you have the full command starting with 3dQwarp ... ?

**Comment by nadkarni-na** [comment]
I can't do ps -aux without rerunning but as I said before the 3dinfo output history section has a -maxlev 7 at the end:
----- HISTORY -----
[nadkarni@DESKTOP-6D094HU: Fri Jan  5 14:36:36 2018] 3dTcat -prefix /mnt/c/Users/nadka/Downloads/forPR/template2/warped_2iters_hetemplate_filenameads.nii.gz /mnt/c/Users/nadka/Downloads/forPR/template2/MSME_MIRCen_RatBrain_atlas_bf3_0_Unifized_for_brain_extraction_resample_warped2.nii.gz /mnt/c/Users/nadka/Downloads/forPR/template2/MSME_MIRCen_RatBrain_atlas_bf5_1_Unifized_for_brain_extraction_resample_warped2.nii.gz /mnt/c/Users/nadka/Downloads/forPR/template2/MSME_MIRCen_RatBrain_atlas_bf7_2_Unifized_for_brain_extraction_resample_warped2.nii.gz /mnt/c/Users/nadka/Downloads/forPR/template2/MSME_MIRCen_RatBrain_atlas_bf9_3_Unifized_for_brain_extraction_resample_warped2.nii.gz
[nadkarni@DESKTOP-6D094HU: Fri Jan  5 14:36:41 2018] 3dTstat -prefix warped_2iters_hetemplate_filenameads_tstat.nii.gz /mnt/c/Users/nadka/Downloads/forPR/template2/warped_2iters_hetemplate_filenameads.nii.gz
[nadkarni@DESKTOP-6D094HU: Fri Jan  5 14:52:45 2018] 3dQwarp -base /mnt/c/Users/nadka/Downloads/forPR/template2/warped_2iters_hetemplate_filenameads_tstat.nii.gz -source /mnt/c/Users/nadka/Downloads/forPR/template2/MSME_MIRCen_RatBrain_atlas_bf9_3_Unifized_for_brain_extraction_resample.nii.gz -inilev 8 -iniwarp /mnt/c/Users/nadka/Downloads/forPR/template2/MSME_MIRCen_RatBrain_atlas_bf9_3_Unifized_for_brain_extraction_resample_warped2_WARP.nii.gz -iwarp -minpatch 11 -noneg -prefix /mnt/c/Users/nadka/Downloads/forPR/template2/MSME_MIRCen_RatBrain_atlas_bf9_3_Unifized_for_brain_extraction_resample_warped3.nii.gz -weight /mnt/c/Users/nadka/Downloads/forPR/template1/affbrainsunionmaskdil5.nii.gz -maxlev 7

**Comment by nadkarni-na** [comment]
and yes am very sure it was the last qwarp

**Comment by nadkarni-na** [comment]
full log is [here](https://1drv.ms/t/s!AiISIfrbeHl7vvFOwcdQ6kKv3gDUlA)

**Comment by salma1601** [comment]
I have something like `cubic patch` that is printed out hundreds of times. Don't you have something like this with `verbose=3`?

**Comment by nadkarni-na** [comment]
not with this data. that happens when the starting image is perfectly cubic, but these images are 160x160x100

**Comment by salma1601** [comment]
I reproduced the bug when no caching is used !
The only difference in the code between caching or not is that I am setting `AFNI_DECONFLICT=OVERWRITE` with `caching=False` and not setting this variable at all when `caching=True`.
The difference between caching or not is the save location of the files.
>not with this data. that happens when the starting image is perfectly cubic, but these images are 160x160x100

You mean Pauline's rat data ? I do have this cubic patch stuff with her data!

**Comment by nadkarni-na** [comment]
what's you afni --version output?
mine is:
Precompiled binary Debian-x86_64-1-gnu: Jun 12 2017 (Version Debian-16.2.07~dfsg.1-5~nd16.04+1)

**Comment by salma1601** [comment]
Precompiled binary Debian-x86_64-1-gnu: Jun 12 2017 (Version Debian-16.2.07~dfsg.1-5~nd14.04+1)

**Comment by nadkarni-na** [comment]
so the only diff is Ubuntu version (for info):
uname -a
Linux DESKTOP-6D094HU 4.4.0-43-Microsoft #1-Microsoft Wed Dec 31 14:42:53 PST 2014 x86_64 x86_64 x86_64 GNU/Linux

**Comment by salma1601** [comment]
Linux finn 3.19.0-25-generic #26~14.04.1-Ubuntu SMP Fri Jul 24 21:16:20 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

**Comment by nadkarni-na** [comment]
So I'm on kernel 4, not 3 (as am on Ubuntu 16)

**Comment by salma1601** [comment]
So there are 2 problems:
- Something is overwritten in the pipeline while it should not, causing a difference between the caching and non caching modes
- just running the same AFNI 3dQwarp with the same data does not have the same behavior

**Comment by salma1601** [comment]
Got the maxlev bug: the qwarp interface is not getting rid of the former arguments in the loop, they are only getting their values updated. So the last `maxlev` value is conserved in the call with the minpatch. This does not occur when caching because caching instanciates a new interface at each time.
I will PR a quick workaround. Sure there is a better way to deal with, but requires I look more into nipype interface functions ...
