### ISSUE TITLE
3dNwarpAdjust

### ISSUE THREAD

**Issue by nadkarni-na** [sammba-mri/sammba-mri#78]
There's a theoretical bug/imperfection in how anats_to_common works. During the non-linear stages, it is possible for systematic biases to accumulate in the non-linear warps. These can be removed by calculating the mean warp (which would be zero if there were no biases, but there usually are), inverting it, applying the inverted warp to the original warps then applying the adjusted warps to the input images to produce an unbiased mean. This is best done using 3dNwarpAdjust, which was written for this exact purpose.

@salma1601 can you add a 3dNwarpAdjust interface to nipype? It only has three options.
I will then modify anats_to_common

**Comment by salma1601** [comment]
Ok, I will do a PR to add it to sammba's externals. I will propose it to nipype then

**Comment by salma1601** [comment]
fixed by #79
