### ISSUE TITLE
Bug in warping anat to functional space

### ISSUE THREAD

**Issue by salma1601** [sammba-mri/sammba-mri#91]
something is going wrong here
https://github.com/sammba-mri/sammba-mri/blob/master/sammba/registration/func.py#L309
that outputs a rotated and translated anatomical in comparison to what it is expected

**Comment by salma1601** [comment]
found the origin of the problem: bias field correction fails with AFNI and was correct with ANTS
![afni](https://user-images.githubusercontent.com/7080143/37044344-81a95ab6-2163-11e8-9d7e-af4ed6b8062e.png)
![ants](https://user-images.githubusercontent.com/7080143/37044345-81cdc522-2163-11e8-969c-07933ab3dac1.png)
@nadkarni-na looks like we need to rely on ANTS for bias field correction

**Comment by nadkarni-na** [comment]
This is an imperfection of FSLView. It orients the images according to how the matrix is stored on the disk. If you look carefully the SI, RL, and AP labels are correctly oriented. It's them that matter, so this is not a bug.

**Comment by nadkarni-na** [comment]
As for the bias field correction with Unifize, it was never a problem in the bash scripts.

**Comment by nadkarni-na** [comment]
Actually can't remember if the bias correction is done on single slices or not, I think it may be done on a 3D volume. In any case, it N4 fails, try N3.

**Comment by nadkarni-na** [comment]
Another option is to tune unifize to be less extreme, e.g. unifize_kwargs={'cl_frac': 0.6}

**Comment by salma1601** [comment]
I think that ANTs bias correction is more powerful than AFNI unifization. I prefer using it rather than head ache from tuning unifize. But the problem is that for the tests to work on travis, I am not sure ANTS can be installed easily. Needs to check this around

**Comment by nadkarni-na** [comment]
With good quality images it is, but we have to deal with a lot of poor ones....hence for us tuning Unifize can be a more universal solution. As for travis, ants should, if anything, be easier than afni. It's also in neurodebian, and better installed- such that it is not necessary to modify the .bashrc to call it.
